FROM node:22-alpine AS development

WORKDIR /app

# Install dependencies required for native builds
RUN apk add --no-cache python3 make g++

# Copy package files
COPY package*.json ./

# Install node dependencies
RUN npm install

# Copy the app source
COPY . .

# Expose port (NestJS default)
EXPOSE 3026

# Start app in dev mode (QA environment)
CMD ["npm", "run", "rebuild:qa"]

